

import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";



const ProfilePage: NextPage = () => {

  //Start fetching asap bc cache
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div>Profile View</div>
      </main>
    </>
  );
};

export default ProfilePage;
